name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    # Par défaut, toutes les commandes 'run:' s'exécutent dans backend-api
    defaults:
      run:
        working-directory: backend-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable (Linux)
        run: chmod +x mvnw

      - name: Build & test with Maven Wrapper
        run: ./mvnw -B clean verify
