name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Important sur Linux : rendre le wrapper exécutable
      - name: Make mvnw executable
        working-directory: ./backend-api
        run: chmod +x mvnw

      - name: Build & test with Maven Wrapper
        working-directory: ./backend-api
        run: ./mvnw -B clean verify

