name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build & test with Maven Wrapper (force cd)
        shell: bash
        run: |
          echo "== ROOT =="
          pwd
          ls -la

          if [ ! -d "backend-api" ]; then
            echo "❌ Dossier 'backend-api' introuvable à la racine. Contenu réel :"
            ls -la
            exit 1
          fi

          echo "== ENTER backend-api =="
          cd backend-api
          pwd
          ls -la

          if [ ! -f "pom.xml" ]; then
            echo "❌ pom.xml introuvable dans backend-api"
            exit 1
          fi
          if [ ! -f "mvnw" ]; then
            echo "❌ mvnw introuvable dans backend-api"
            exit 1
          fi

          chmod +x mvnw
          ./mvnw -B clean verify
