name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Debug: vérifier où on se trouve et ce qu'il y a dedans
      - name: Debug paths (root)
        run: |
          pwd
          ls -la

      - name: Debug paths (backend-api)
        working-directory: backend-api
        run: |
          pwd
          ls -la
          test -f pom.xml && echo "pom.xml found ✅" || (echo "pom.xml missing ❌" && exit 1)
          test -f mvnw && echo "mvnw found ✅" || (echo "mvnw missing ❌" && exit 1)

      - name: Make mvnw executable (Linux)
        working-directory: backend-api
        run: chmod +x mvnw

      - name: Build & test with Maven Wrapper
        working-directory: backend-api
        run: ./mvnw -B clean verify
