name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x backend-api/mvnw

      - name: Build & test with Maven Wrapper
        run: ./backend-api/mvnw -B -f backend-api/pom.xml clean verify

      # (fix) Redonner l'exécutable juste avant Sonar pour éviter "Permission denied"
      - name: Ensure mvnw is executable (for Sonar step)
        run: chmod +x backend-api/mvnw

      - name: SonarCloud analysis
        run: |
          ./backend-api/mvnw -B verify sonar:sonar -DskipTests=false \
            -Dsonar.projectKey=etchakou_docker-td \
            -Dsonar.organization=etchakou \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Normalize mvnw line endings and make executable
        run: |
          sed -i 's/\r$//' backend-api/mvnw
          chmod +x backend-api/mvnw
          head -n 1 backend-api/mvnw

      - name: SonarCloud analysis
        run: |
          ./backend-api/mvnw -B verify sonar:sonar -DskipTests=false \
            -Dsonar.projectKey=etchakou_docker-td \
            -Dsonar.organization=etchakou \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

