name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x backend-api/mvnw

      - name: Build & test with Maven Wrapper
        run: ./backend-api/mvnw -B -f backend-api/pom.xml clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & (conditionally) push backend-api image
        uses: docker/build-push-action@v6
        with:
          context: ./backend-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-td-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build & (conditionally) push db image
        if: ${{ hashFiles('db/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./db
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-td-db:latest
          push: ${{ github.ref == 'refs/heads/main' }}
